#!/bin/bash
# Converts ASCII text files to PDF

set -o errexit
# debugging
#set -x

PS2PDF_ARGS="-sPAPERSIZE=a4 -dOptimize=true -dEmbedAllFonts=true"
INPUT_FILE="$1"
OUTPUT_FILE="$2"

EXIT_BADARGS=2


function print_usage()
{
	echo "Invalid number of arguments."
	echo "Usage: text2pdf input_file [ output_file | - ]"
}


# wrong number of args?
if [ "$#" = 0 ] || [ "$#" -ge 3 ]
then
    print_usage
    exit ${EXIT_BADARGS}
else
    # check input file
    if [ ! -f "${INPUT_FILE}" ]
    then
        echo "${INPUT_FILE}: No regular file. Exit."
        exit ${EXIT_BADARGS}
    else
        if [ ! -r "${INPUT_FILE}" ]
        then
            echo "${INPUT_FILE}: No read permission. Exit"
        fi
    fi
    
    if [ "$#" = 1 ]
    then
        OUTPUT_FILE="${INPUT_FILE}.pdf"
    fi
fi

text2ps "${INPUT_FILE}" - | ps2pdf ${PS2PDF_ARGS} -sOutputFile="${OUTPUT_FILE}" -

exit $?
