#!/bin/bash
# Converts ASCII text files to PDf


# check for commandline arguments
if [ "$#" = 0 ] ; then
	echo "no target file specified."
	echo "usage: text2pdf file"
fi


# do conversion
for ARG in "$@" ; do


	if [ -f $ARG ] ; then
	
		a2ps --tabsize=4 --portrait --highlight-level=heavy --prologue=color --columns=1 --font-size=11 --media=A4 --chars-per-line=80 --line-numbers=1 --output=- $ARG \
		| ps2pdf -sPAPERSIZE=a4 -dOptimize=true -dEmbedAllFonts=true - $ARG.pdf
	
		if [ -f "$ARG.pdf" ] ; then
			echo "$ARG converted. Saved to $ARG.pdf"
		else
			echo "error: conversion mied have been aborted, new file does not exist"
		fi
	
	else
		echo "$ARG skipped: file does not exist"
	fi
done
