#!/bin/bash
# Converts ASCII text files to PostScript

set -o errexit
# debugging
#set -x

A2PS_ARGS="--tabsize=4 \
           --portrait \
           --highlight-level=heavy \
           --prologue=color \
           --columns=1 \
           --rows=1 \
           --font-size=11 \
           --media=A4 \
           --chars-per-line=80 \
           --line-numbers=1 \
           --encoding=ASCII
           --quiet"
INPUT_FILE="$1"
OUTPUT_FILE="$2"

EXIT_BADARGS=2


function print_usage()
{
	echo "Invalid number of arguments."
	echo "Usage: text2ps [ input_file | - ] [ output_file | - ]"
    echo 
    echo "Note: 'text2ps -' is treated as an alias for 'text2ps - -'"
}

# wrong number of args?
if [ "$#" = 0 ] || [ "$#" -ge 3 ]
then
    print_usage
    exit ${EXIT_BADARGS}
fi

if [ ! "${INPUT_FILE}" = "-" ]
then
    # check input file
    if [ ! -e "${INPUT_FILE}" ]
    then
        echo "${INPUT_FILE}: file does not exist"
        exit ${EXIT_BADARGS}
    fi
    if [ ! -f "${INPUT_FILE}" ]
    then
        echo "${INPUT_FILE}: not a regular file"
        exit ${EXIT_BADARGS}
    fi
    if [ ! -r "${INPUT_FILE}" ]
    then
        echo "${INPUT_FILE}: no read permission"
        exit ${EXIT_BADARGS}
    fi
    if [ ! -s "${INPUT_FILE}" ]
    then
        echo "${INPUT_FILE}: file is empty"
        exit ${EXIT_BADARGS}
    fi
    
    if [ "$#" = 1 ]
    then
        OUTPUT_FILE="${INPUT_FILE}.ps"
    fi
else
    # Files called '-.ps' are not nice, so we use stdout
    if [ "$#" = 1 ]
    then
        OUTPUT_FILE="-"
    fi
fi

a2ps ${A2PS_ARGS} --output="${OUTPUT_FILE}" "${INPUT_FILE}"

exit $?
