#!/bin/bash
# Converts ASCII text files to PDF

set -o errexit
# debugging
#set -x

PS2PDF_ARGS="-sPAPERSIZE=a4 \
             -dOptimize=true \
             -dEmbedAllFonts=true"
INPUT_FILE="$1"
OUTPUT_FILE="$2"

EXIT_SUCCESS=0
EXIT_BADARGS=2


function print_usage()
{
	echo "Usage: text2pdf [ input_file | - ] [ output_file | - ]"
    echo
    echo "Note: 'text2pdf -' is treated as an alias for 'text2pdf - -'"
}


# --help
if [ "$1" = "--help" ]
then
    print_usage
    exit ${EXIT_SUCCESS}
fi


# wrong number of args?
if [ "$#" = 0 ] || [ "$#" -ge 3 ]
then
	echo "Invalid number of arguments."
    echo
    print_usage
    exit ${EXIT_BADARGS}
fi

if [ "$#" = 1 ]
then
    if [ ! "${INPUT_FILE}" = "-" ]
    then
        OUTPUT_FILE="${INPUT_FILE}.pdf"
    else
        OUTPUT_FILE="-"
    fi
fi

if [ ! "${OUTPUT_FILE}" = "-" ]
then
    if [ ! -w "${OUTPUT_FILE}" ]
    then
        echo "${OUTPUT_FILE}: no write permission"
        exit ${EXIT_BADARGS}
    fi
fi

text2ps "${INPUT_FILE}" - | ps2pdf ${PS2PDF_ARGS} -sOutputFile="${OUTPUT_FILE}" -

exit $?
