#!/bin/bash
# text2ps: Create PostScript files from ASCII text
#
# Copyright (C) 2009 Michael Fiedler <michael.fiedler87@googlemail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

set -o errexit
# debugging
#set -x

A2PS_ARGS="--tabsize=4 \
           --portrait \
           --highlight-level=heavy \
           --prologue=color \
           --columns=1 \
           --rows=1 \
           --font-size=11 \
           --media=A4 \
           --chars-per-line=80 \
           --line-numbers=1 \
           --encoding=ASCII
           --quiet"
FIRST_ARG="$1"
SECOND_ARG="$2"
INPUT_FILE="${FIRST_ARG}"
OUTPUT_FILE="${SECOND_ARG}"

EXIT_SUCCESS=0
EXIT_ERROR=1
EXIT_BADARGS=2


function print_usage()
{
	echo "Usage: text2ps [ input_file | - ] [ output_file | - ]"
    echo 
    echo "Note: 'text2ps -' is treated as an alias for 'text2ps - -'"
}


# --help
if [ "${FIRST_ARG}" = "--help" ]
then
    print_usage
    exit ${EXIT_SUCCESS}
fi


# wrong number of args?
if [ "$#" = 0 ] || [ "$#" -ge 3 ]
then
	echo "Invalid number of arguments."
    echo
    print_usage
    exit ${EXIT_BADARGS}
fi

if [ ! "${INPUT_FILE}" = "-" ]
then
    # check input file
    if [ ! -e "${INPUT_FILE}" ]
    then
        echo "${INPUT_FILE}: file does not exist"
        exit ${EXIT_BADARGS}
    fi
    if [ ! -f "${INPUT_FILE}" ]
    then
        echo "${INPUT_FILE}: not a regular file"
        exit ${EXIT_BADARGS}
    fi
    if [ ! -r "${INPUT_FILE}" ]
    then
        echo "${INPUT_FILE}: no read permission"
        exit ${EXIT_BADARGS}
    fi
    if [ ! -s "${INPUT_FILE}" ]
    then
        echo "${INPUT_FILE}: file is empty"
        exit ${EXIT_BADARGS}
    fi
    
    if [ "$#" = 1 ]
    then
        OUTPUT_FILE="${INPUT_FILE}.ps"
    fi
else
    # Files called '-.ps' are not nice, so we use stdout
    if [ "$#" = 1 ]
    then
        OUTPUT_FILE="-"
    fi
fi

if [ ! "${OUTPUT_FILE}" = "-" ]
then
    if [ ! -w "${OUTPUT_FILE}" ]
    then
        echo "${OUTPUT_FILE}: no write permission"
        exit ${EXIT_BADARGS}
    fi
fi

a2ps ${A2PS_ARGS} --output="${OUTPUT_FILE}" "${INPUT_FILE}"

exit $?
